name: Repository Information

on:
  workflow_dispatch:
  push:

jobs:
  repo-info:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Repository Information
      run: |
        echo "Action: show-information"
        echo "Repository Name: ${{ github.repository }}"
        echo "Repository Owner: ${{ github.repository_owner }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Event Name: ${{ github.event_name }}"
        echo "Workspace: ${{ github.workspace }}"
        echo "SHA: ${{ github.sha }}"
